### ISSUE TITLE
Cocos2d-v3. CCPhysicsNode -> CCSpriteBatchNode -> CCSprite with physicsBody not working

### ISSUE THREAD

**Issue by nsleader** [cocos2d/cocos2d-objc#564]
Sprite does not respond to physics. However, the physical body responds to physics (I saw this with debugDraw = YES).

```
// self - CCScene
CCPhysicsNode *physicsNode = [CCPhysicsNode node];
physicsNode.debugDraw = YES;
physicsNode.gravity = ccp(0, -100);
[self addChild:physicsNode];

[physicsNode addChild:batchNode];

CCSprite *s = [CCSprite spriteWithImageNamed:@"Prep0.png"];
s.physicsBody = [CCPhysicsBody bodyWithCircleOfRadius:30 andCenter:ccp(s.contentSize.width/2.0f, s.contentSize.height/2.0f)];
[batchNode addChild:s];
```

This code should work?

**Comment by slembcke** [comment]
It should yes. Batched sprites use a pretty unique code path. It got missed in testing apparently.

**Comment by slembcke** [comment]
Fixed. Will be pushed shortly.

**Comment by rabzu** [comment]
Has this been fixed yet? I have the same problem!

**Comment by jjxtra** [comment]
It's fixed with the latest code from Github. Don't use RC1.

**Comment by ghost** [comment]
Well. I still see the problem. I use a ccsprite with two ccsprites, but only one physics body
