### ISSUE TITLE
Current v3.2 branch is broken...

### ISSUE THREAD

**Issue by iMobCoding** [cocos2d/cocos2d-objc#995]
There are a lot of uncommitted files in v3.2 branch due to ObjectAL changes, I think it's submodule now? Also Xcode projects should be updated for it...

**Comment by slembcke** [comment]
Have you updated the submodule?

`git submodule update --init --recursive`

The way Git handles submodules is really really dumb. I end up running that command a dozen times a day because Git's default behavior is to think that you don't want to check out the corresponding submodule commit when switching branches. -_-

**Comment by iMobCoding** [comment]
I am using SourceTree as an GUI for git, and it should auto update submodules when switching branches (I don't even see this submodule in the list, only Chipmunk there). But anyway, I ran manual update and it's still the same. Please check v3.2 branch as I think something wasn't properly merged...

**Comment by slembcke** [comment]
Apologies, I was looking at the wrong branch. I forgot to push last v3.2 last time I was merging into it was ahead by 10 commits. If you pull again it should be working.

Thanks for catching that!

**Comment by iMobCoding** [comment]
I still see about 200 uncommitted files there in v3.2 branch. I think they are from develop branch...

**Comment by slembcke** [comment]
Hmm. Will try checking out a fresh copy of the repository to double check. My working copy builds ok and has no unpushed changes. There's been a lot of weird stuff happening with the submodules in the last couple weeks that could have gone awry.

**Comment by iMobCoding** [comment]
Correct me if I am wrong... Develop branch has ObjectAL as submodule now (with ogg and tremor), but v3.2 branch kept old structure? If so, then somehow ObjectAL files from develop branch are shown as uncommitted "untracked" files for me in v3.2. If I try to reset/delete them, then I break the submodule for ObjAL in develop branch. Somehow things got mixed. I tried cloning new repo and if I check out only v3.2 branch everything seems ok, but as soon as I check out develop branch, the v3.2 breaks... I am sure it's something trivial about how the submodules are setup but it's beyond me to fix it :)

**Comment by slembcke** [comment]
Oooh I see. That is Git's fault for how it deals with submodules. I have to deal with that almost every day. When you check out the develop branch it pulls in a bunch of new files that don't get deleted when switching back to v3.2. The easiest thing to do is to delete the entire externals folder and check it out again, and update the submodules. Very annoying. :-\

**Comment by iMobCoding** [comment]
Uh I am sure there is a way to handle that differently. For example, SpriteBuilder repo has 1.2 and develop branches. Both share 3 submodules, plus develop branch has Sparkle submodule. And that directory isn't deleted when switching branches but there are not bunch of uncommitted files when I switch?
